# Generated by Django 4.1.6 on 2023-08-08 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0002_problemsetduringediting'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
