# Generated by Django 4.1.6 on 2023-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0003_problemset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
