# Generated by Django 4.1.6 on 2023-08-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0005_usertoproblemset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoproblemset',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertoproblemset',
            name='surrendered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertoproblemset',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
