# Generated by Django 4.1.6 on 2023-08-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_usertoproblemset_solved_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoproblemset',
            name='total_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
