# Generated by Django 4.1.6 on 2023-08-05 09:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_remove_solution_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('comment', models.TextField(null=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.solution')),
            ],
        ),
    ]
