# Generated by Django 4.1.6 on 2023-07-08 07:15

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_statement',
            field=django_quill.fields.QuillField(default='ici'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(null=True, upload_to='base/files/contents'),
        ),
    ]
