# Generated by Django 4.1.6 on 2023-07-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usertoproblem_began_surrendering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
