# Generated by Django 4.1.6 on 2023-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_problem_content_remove_solution_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoproblem',
            name='is_watching',
            field=models.BooleanField(default=False),
        ),
    ]
