# Generated by Django 4.1.6 on 2023-08-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_problem_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='voters',
        ),
    ]
