# Generated by Django 4.1.6 on 2023-07-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_usertoproblem_is_watching'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoproblem',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
