# Generated by Django 4.1.6 on 2023-07-09 07:19

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_usertoproblem_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_statement',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='upvote_counter',
            field=models.IntegerField(default=0),
        ),
    ]
