# Generated by Django 4.2.3 on 2023-07-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_solution_content_solution_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='voters',
            field=models.JSONField(default={'voters': True}, verbose_name='Voters'),
        ),
    ]
