# Generated by Django 4.1.6 on 2023-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_solution_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
