# Generated by Django 4.1.6 on 2023-08-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
        ('base', '0007_problem_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoproblem',
            name='seen_in_problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problemset.problemset'),
        ),
    ]
