# Generated by Django 4.1.6 on 2023-08-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_usertoproblem_seen_in_problemset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertoproblem',
            unique_together={('problem', 'user')},
        ),
    ]
