# Generated by Django 4.1.6 on 2023-07-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_solutionvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='problem',
        ),
        migrations.AddField(
            model_name='comment',
            name='solution',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='base.solution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
    ]
