# Generated by Django 4.1.6 on 2023-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_usertoproblem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoproblem',
            name='surrendering_as_solved',
            field=models.BooleanField(default=False),
        ),
    ]
