# Generated by Django 4.1.6 on 2023-08-05 14:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_problem_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem_statement', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.problem')),
            ],
        ),
    ]
