# Generated by Django 4.1.6 on 2023-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemhistory',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
