# Generated by Django 4.1.6 on 2023-07-15 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcommentnotification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newcommentnotification',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='newcommentnotification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='newcommentnotification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='newcommentnotification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newcommentnotification',
            name='user',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='newcommentnotification',
            name='notification_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification'),
            preserve_default=False,
        ),
    ]
