# Generated by Django 4.1.6 on 2023-07-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_newcommentnotification_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='comment', max_length=20),
            preserve_default=False,
        ),
    ]
