# Generated by Django 4.1.6 on 2023-07-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_comment_upvote_counter_commentvote'),
        ('notifications', '0003_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSolutionNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.solution')),
            ],
            bases=('notifications.notification',),
        ),
    ]
