# Generated by Django 4.1.6 on 2023-08-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_problem_source'),
        ('notifications', '0005_newproblemnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproblemnotification',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.problem'),
        ),
    ]
